version: "3.1"

services:
  php:
    container_name: sspanel
    image: baiyuetribe/sspanel:php
    restart: always
    volumes:
      - /opt/sspanel/config:/var/www/html/config
      - /opt/sspanel/public/images:/var/www/html/public/images
    depends_on:
      - mysql    
    networks:
      - frontend
      - backend
  nginx:
    image: baiyuetribe/sspanel:nginx 
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    volumes:
      - /opt/sspanel/mysql:/var/lib/mysql
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_DATABASE=sspanel"
      - "MYSQL_ROOT_PASSWORD=数据库密码"
    ports:
        - "3306:3306"
    networks:
        - backend 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
        - mysql
    environment:
        PMA_HOST: mysql
        TZ: 'Asia/Shanghai'
    networks:
        - backend                 
    depends_on:
      - mysql
volumes:
  sspanel_config:
  sspanel_images:
  
networks:
  frontend:
  backend:
